import { defineConfig } from 'tsup'

export default defineConfig({
  tsconfig: 'tsconfig.build.json',
  entry: {
    'index': 'index.ts',
    'core/index': 'core/index.ts',
    'content/index': 'content/index.ts',
    'dsl/index': 'dsl/index.ts',
    'dsl/dispatcher': 'dsl/dispatcher.ts',
    'engine/index': 'engine/index.ts',
    'engine/triples': 'engine/triples.ts',
    'engine/query': 'engine/query.ts',
    'engine/merge': 'engine/merge.ts',
    'engine/diff': 'engine/diff.ts',
    'engine/completeness': 'engine/completeness.ts',
    'engine/apply': 'engine/apply.ts',
    'engine/applyM0': 'engine/applyM0.ts',
    'engine/inverse': 'engine/inverse.ts',
    'engine/analyze': 'engine/analyze.ts',
    'engine/inheritance': 'engine/inheritance.ts',
    'engine/instanceTriples': 'engine/instanceTriples.ts',
    'engine/instanceValidation': 'engine/instanceValidation.ts',
    'engine/m0Triples': 'engine/m0Triples.ts',
    'engine/serialize': 'engine/serialize.ts',
    'engine/normalize': 'engine/normalize.ts',
    'export/index': 'export/index.ts',
    'generate/index': 'generate/index.ts',
    'generate/app': 'generate/app.ts',
    'generate/domainLayer': 'generate/domainLayer.ts',
    'generate/export': 'generate/export.ts',
    'generate/download': 'generate/download.ts',
    'generate/selfProjection': 'generate/selfProjection.ts',
    'meta/index': 'meta/index.ts',
    'meta/customTypes': 'meta/customTypes.ts',
    'meta/i18n': 'meta/i18n.ts',
    'meta/ontology': 'meta/ontology.ts',
    'meta/vocabulary': 'meta/vocabulary.ts',
    'meta/fields': 'meta/fields.ts',
    'meta/facets': 'meta/facets.ts',
    'migrations/index': 'migrations/index.ts',
    'runtime/index': 'runtime/index.ts',
    'runtime/pipelineRuntime': 'runtime/pipelineRuntime.ts',
    'runtime/queryBuilder': 'runtime/queryBuilder.ts',
    'runtime/typedCollection': 'runtime/typedCollection.ts',
    'runtime/writebackRuntime': 'runtime/writebackRuntime.ts',
    'runtime/inMemoryRepository': 'runtime/inMemoryRepository.ts',
    'runtime/providers/localProvider': 'runtime/providers/localProvider.ts',
    'types/index': 'types/index.ts',
    'types/context': 'types/context.ts',
    'types/commands': 'types/commands.ts',
    'types/query': 'types/query.ts',
    'types/branch': 'types/branch.ts',
    'types/commits': 'types/commits.ts',
    'types/instance': 'types/instance.ts',
    'types/m0': 'types/m0.ts',
    'util/templates': 'util/templates.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  outDir: 'dist',
  target: 'node18',
  external: ['immer', 'klona', 'nanoid'],
})
