/**
 * TypedCollection - a type-safe, validated wrapper over InstanceRepository
 * for a single entity type. Bridges typed domain objects (e.g. Product)
 * and the generic M0 storage layer.
 *
 * Part of the domain model layer contract: every generated layer produces
 * a DomainRepository with TypedCollection<T> per Thing.
 */

import type { InstanceRepository, QueryOptions } from './types'
import type { EntityInstance } from '../types/instance'
import type { SetExpr } from '../types/query'
import type { RootContext } from '../types/context'

// ── Public types ────────────────────────────────────────────────────────────

/** A domain object (typed) paired with its instance metadata. */
export interface TypedInstance<T> {
  /** Instance ID (generated by the repository). */
  id: string
  /** The validated domain data. */
  data: T
  /** ISO timestamp of creation. */
  createdAt: string
  /** ISO timestamp of last update. */
  updatedAt: string
}

/** Type-safe CRUD + query for a single entity type. */
export interface TypedCollection<T> {
  /** Create a validated instance. The schema runs before storage. */
  create(data: T): Promise<TypedInstance<T>>
  /** Find by instance ID. Returns null if not found. */
  findById(id: string): Promise<TypedInstance<T> | null>
  /** Find all instances of this entity type. */
  findAll(options?: QueryOptions): Promise<TypedInstance<T>[]>
  /** Update fields on an existing instance. Validates the partial changes. */
  update(id: string, changes: Partial<T>): Promise<TypedInstance<T>>
  /** Delete an instance by ID. */
  delete(id: string): Promise<void>
  /** Query using the raw set algebra. */
  query(expr: SetExpr): Promise<TypedInstance<T>[]>
  /** Count instances (optionally with a filter expression). */
  count(filter?: SetExpr): Promise<number>
}

// ── Configuration ───────────────────────────────────────────────────────────

/** Schema validator interface - compatible with Zod's .parse() and .partial().parse(). */
export interface SchemaValidator<T> {
  parse(data: unknown): T
  partial(): { parse(data: unknown): Partial<T> }
}

export interface TypedCollectionConfig<T> {
  /** The M1 Thing ID this collection manages instances of. */
  thingId: string
  /** Schema validator (Zod or compatible). Runs on create/update. */
  schema: SchemaValidator<T>
  /** The underlying generic storage. */
  repo: InstanceRepository
  /** The M1 model (needed for set algebra evaluation). */
  model: RootContext
}

// ── Factory ─────────────────────────────────────────────────────────────────

function toTypedInstance<T>(instance: EntityInstance): TypedInstance<T> {
  // EntityInstance stores attributes as Record<string, AttributeValue>.
  // For TypedCollection consumers, we flatten to plain values.
  const data: Record<string, unknown> = {}
  for (const [key, attr] of Object.entries(instance.attributes)) {
    data[key] = attr.value
  }
  return {
    id: instance.id,
    data: data as T,
    createdAt: instance.createdAt,
    updatedAt: instance.updatedAt ?? instance.createdAt,
  }
}

export function createTypedCollection<T>(
  config: TypedCollectionConfig<T>,
): TypedCollection<T> {
  const { thingId, schema, repo, model } = config

  return {
    async create(data) {
      const validated = schema.parse(data)
      const instance = await repo.create(thingId, validated as Record<string, unknown>)
      return toTypedInstance<T>(instance)
    },

    async findById(id) {
      const instance = await repo.findById(id)
      if (!instance || instance.thingId !== thingId) return null
      return toTypedInstance<T>(instance)
    },

    async findAll(options) {
      const instances = await repo.findByThing(thingId, options)
      return instances.map(i => toTypedInstance<T>(i))
    },

    async update(id, changes) {
      schema.partial().parse(changes)
      const instance = await repo.update(id, changes as Record<string, unknown>)
      return toTypedInstance<T>(instance)
    },

    async delete(id) {
      await repo.delete(id)
    },

    async query(expr) {
      const instances = await repo.query(expr, model)
      return instances
        .filter(i => i.thingId === thingId)
        .map(i => toTypedInstance<T>(i))
    },

    async count(filter) {
      const expr: SetExpr = filter ?? { op: 'base', objectType: thingId }
      const instances = await repo.query(expr, model)
      return instances.filter(i => i.thingId === thingId).length
    },
  }
}
