// @generated - do not edit manually
// Generated by ontology/codegen/generate.ts from the ontology registries.
// Source of truth: meta/typeRegistry.ts + meta/ontology.ts + meta/fields.ts

import type { StoredPredicateId, FacetKey } from '../meta/ontology'

// ValueConstraint and ValueTypeDef live in meta/valueTypes.ts (M2 concepts).
// Imported for local use and re-exported so consumers get all types from one file.
import type { ValueConstraint, ValueTypeDef } from '../meta/valueTypes'
export type { ValueConstraint, ValueTypeDef } from '../meta/valueTypes'

export type SymbolMode = 'title' | 'card'

export type DurationUnit = 'seconds' | 'minutes' | 'hours' | 'days' | 'weeks'

export type ScheduleFrequency = 'hourly' | 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly'

export type ThingStereotype = 'entity' | 'value-object' | 'aggregate-root' | 'reference-data' | 'goal' | 'risk' | 'assumption' | 'milestone'

export type PersonaStereotype = 'human' | 'team' | 'system' | 'external' | 'customer'

export type MeasureStereotype = 'metric' | 'aggregator' | 'financial'

export type FunctionStereotype = 'formatter' | 'calculator' | 'predicate' | 'transformer' | 'lookup' | 'validator'

export type FunctionPurity = 'pure'

export type FunctionVisibility = 'public' | 'internal'

export type FunctionBodyKind = 'expression' | 'typescript'

export type FunctionCardinality = 'scalar' | 'array'

export type DataSourceTransport = 'http' | 'graphql' | 'sql' | 'file' | 'object-storage' | 'mcp' | 'webhook-in' | 'email' | 'synthetic'

export type DataSourceAuthType = 'none' | 'bearer' | 'basic' | 'oauth2' | 'api-key' | 'sasl'

export type DataSourceStereotype = 'read-only' | 'read-write' | 'write-only' | 'event-stream'

export type DataSourceConnectionStatus = 'untested' | 'connected' | 'error' | 'expired'

export type DataSourceEnvironment = 'simulation' | 'dev' | 'staging' | 'prod'

export type PipelineStrategy = 'materialize' | 'federate' | 'hybrid'

export type PipelineDirection = 'pull' | 'push' | 'two-way'

export type PipelineStereotype = 'import' | 'export' | 'sync' | 'stream' | 'batch'

export type PipelineRunStatus = 'ok' | 'partial' | 'failed' | 'running'

export type PipelineSchedule =
  | { kind: 'cron'; expression: string }
  | { kind: 'on-demand' }
  | { kind: 'continuous' }

export type InterfaceKind = 'application' | 'page' | 'layout' | 'component' | 'form' | 'dashboard' | 'design-tokens' | 'api' | 'endpoint' | 'webhook' | 'notification' | 'report'

export type AssertionScope = 'all' | 'tagged' | 'entityType'

export type ContextMapPattern = 'partnership' | 'customer-supplier' | 'conformist' | 'anticorruption-layer' | 'open-host-service' | 'published-language' | 'shared-kernel' | 'separate-ways'

export type FacetType = FacetKey

export type LinkPredicate = StoredPredicateId

export type MediaRef =
  | { kind: 'blob'; id: string; mimeType: string }
  | { kind: 'url'; href: string; mimeType?: string }

export type ActionCondition =
  | { type: 'state'; thingId: string; stateId: string; description?: string }
  | { type: 'field'; thingId: string; attribute: string; operator: 'exists' | 'equals' | 'gt' | 'lt'; value?: string; description?: string }
  | { type: 'text'; description: string }

export type AssertionRule =
  | { type: 'min-facet-count'; facetType: string; min: number }
  | { type: 'max-facet-count'; facetType: string; max: number }
  | { type: 'requires-link'; predicate: string }
  | { type: 'requires-tag'; tag: string }
  | { type: 'requires-outgoing-link'; predicate: string; min?: number }
  | { type: 'requires-incoming-link'; predicate: string; min?: number }
  | { type: 'requires-field'; field: string; facetTypes?: string[] }

export type FieldSource =
  | { from: 'parameter'; paramName: string }
  | { from: 'attribute'; thingRef: string; attribute: string }
  | { from: 'static'; value: unknown }
  | { from: 'computed'; expression: string }
  | { from: 'currentUser' }
  | { from: 'currentTime' }

export interface SymbolStyle {
  fontSize?: 'sm' | 'base' | 'lg' | 'xl' | '2xl'
  fontWeight?: 'normal' | 'medium' | 'bold'
  textAlign?: 'left' | 'center' | 'right'
  colorToken?: string
}

export interface RichDocMark {
  type: string
  attrs?: Record<string, unknown>
}

export interface RichDocNode {
  type: string
  id?: string
  attrs?: Record<string, unknown>
  content?: RichDocNode[]
  marks?: RichDocMark[]
  text?: string
}

export interface RichDoc {
  type: 'doc'
  content: RichDocNode[]
}

export interface Symbol {
  uri: string
  label?: string
  content: string
  contentDoc?: RichDoc
  mode?: SymbolMode
  modePinned?: boolean
  style?: SymbolStyle
  language?: string
  collapsed?: boolean
  tags?: readonly string[]
  attachment?: MediaRef
}

export interface UserDefinedFieldDef {
  name: string
  type: 'string' | 'number' | 'boolean' | 'text' | 'select' | 'array-string'
  label?: string
  description?: string
  required?: boolean
  defaultValue?: unknown
  enumValues?: string[]
}

export interface UserDefinedEntityType {
  id: string
  label: string
  singular: string
  pluralKey: string
  description: string
  fields: UserDefinedFieldDef[]
  color: string
  icon?: string
  tier: 1 | 2 | 3
}

export interface ThingAttribute {
  name: string
  type: string
  referencedThingId?: string
  referenceType?: 'association' | 'composition'
  enumValues?: string[]
  unit?: string
  currencyCode?: string
  valueTypeId?: string
  constraints?: ValueConstraint[]
  required?: boolean
  unique?: boolean
  indexed?: boolean
  defaultValue?: unknown
}

export interface Duration {
  value: number
  unit: DurationUnit
}

export interface Schedule {
  frequency: ScheduleFrequency
  interval?: number
  description?: string
}

export interface WorkflowSla {
  maxDuration: Duration
  escalation?: string
}

export interface ThingStateTransition {
  id: string
  targetStateId: string
  label?: string
  guard?: string
  triggerActionId?: string
  triggerEventId?: string
}

export interface ThingState {
  id: string
  name: string
  description?: string
  initial?: boolean
  terminal?: boolean
  transitions?: ThingStateTransition[]
}

export interface WorkflowTrigger {
  type: 'manual' | 'event' | 'action' | 'schedule'
  refId?: string
  description?: string
  schedule?: Schedule
}

export interface WorkflowTransition {
  id: string
  targetStepId: string
  label: string
  guard?: string
}

export interface WorkflowStepFacetRef {
  facetType: string
  facetUri: string
  contextUri?: string
}

export interface WorkflowStep {
  id: string
  name?: string
  description?: string
  transitions?: WorkflowTransition[]
  sla?: WorkflowSla
  expectedDuration?: Duration
  facetRef?: WorkflowStepFacetRef
}

export interface SchemaField {
  name: string
  sourceThingId?: string
  sourceAttributeName?: string
  type?: string
  description?: string
}

export interface FunctionParameter {
  name: string
  sourceThingId?: string
  sourceAttribute?: string
  type?: string
  required: boolean
  cardinality: FunctionCardinality
  description?: string
}

export interface FunctionReturnType {
  sourceThingId?: string
  type?: string
  cardinality: FunctionCardinality
  description?: string
}

export interface FunctionSignature {
  parameters: FunctionParameter[]
  returns: FunctionReturnType
}

export interface FunctionBody {
  kind: FunctionBodyKind
  source: string
  dependencies?: string[]
}

export interface FieldMapping {
  source: string
  transform?: string
  defaultValue?: unknown
}

export interface LinkMapping {
  predicate: string
  targetThingId: string
  match: string
}

export interface PipelineMapping {
  iterate?: string
  identity: { externalId: string }
  fields: Record<string, string | FieldMapping>
  links?: LinkMapping[]
  filter?: string
}

export interface RateLimitConfig {
  requestsPerSecond: number
  burstSize?: number
}

export interface MeasureTarget {
  min?: number
  max?: number
  direction: 'higher-is-better' | 'lower-is-better' | 'range'
}

export interface AssertionSelector {
  scope: AssertionScope
  tags?: string[]
  entityTypes?: string[]
}

export interface Assertion {
  id: string
  name: string
  description?: string
  selector: AssertionSelector
  rule: AssertionRule
  severity: 'error' | 'warning' | 'info'
  enabled: boolean
  origin?: 'ontology' | 'user'
}

export interface AssertionViolation {
  assertionId: string
  assertionName: string
  entityId: string
  entityName: string
  entityType?: string
  message: string
  severity: 'error' | 'warning' | 'info'
}

export interface Link {
  uri: string
  predicate: LinkPredicate
  sourceUri: string
  targetUri: string
  label?: string
  description?: string
  pattern?: ContextMapPattern
  metadata?: Record<string, unknown>
}

export interface ActionParameter {
  name: string
  sourceThingId?: string
  sourceAttribute?: string
  type?: string
  valueTypeId?: string
  required?: boolean
  defaultValue?: unknown
  description?: string
}

export interface MutationRule {
  type: 'create' | 'modify' | 'delete' | 'transitionState' | 'createLink' | 'deleteLink'
  thingId?: string
  fieldMappings?: Record<string, FieldSource>
  targetStateId?: string
  predicate?: string
  sourceRef?: string
  targetRef?: string
}

export interface SideEffectRule {
  type: 'emit' | 'notify' | 'webhook' | 'invoke'
  eventId?: string
  payloadMappings?: Record<string, FieldSource>
  channel?: string
  recipientRef?: string
  template?: string
  url?: string
  method?: string
  bodyMappings?: Record<string, FieldSource>
  actionId?: string
  inputMappings?: Record<string, FieldSource>
}

export interface ActionAuthorization {
  mode: 'performers-only' | 'any-authenticated' | 'custom'
  customCondition?: string
}

export interface Thing {
  uri: string
  name: string
  tags?: string[]
  stereotype?: ThingStereotype
  definition: string
  thingRole?: 'root' | 'part' | 'descriptor'
  attributes: ThingAttribute[]
  rules?: string[]
  states?: ThingState[]
}

export interface Persona {
  uri: string
  name: string
  tags?: string[]
  description: string
  role: string
  personaType: PersonaStereotype
  topologyType?: 'stream-aligned' | 'platform' | 'enabling' | 'complicated-subsystem'
}

export interface Port {
  uri: string
  name: string
  tags?: string[]
  description: string
  direction: 'produces' | 'consumes'
}

export interface Action {
  uri: string
  name: string
  tags?: string[]
  description: string
  expectedDuration?: Duration
  type: 'command' | 'query' | 'intent'
  preconditions?: ActionCondition[]
  postconditions?: ActionCondition[]
  parameters?: ActionParameter[]
  mutations?: MutationRule[]
  sideEffects?: SideEffectRule[]
  authorization?: ActionAuthorization
}

export interface Workflow {
  uri: string
  name: string
  tags?: string[]
  description: string
  trigger?: WorkflowTrigger
  steps: WorkflowStep[]
  triggerStepId?: string
  sla?: WorkflowSla
}

export interface Interface {
  uri: string
  name: string
  tags?: string[]
  description: string
  media?: MediaRef
  kind: InterfaceKind
  route?: string
  regions?: string[]
  props?: SchemaField[]
  slots?: string[]
  emits?: string[]
  sourceThingId?: string
  basePath?: string
  auth?: 'none' | 'api-key' | 'bearer' | 'oauth'
  httpMethod?: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  path?: string
  requestSchema?: SchemaField[]
  responseSchema?: SchemaField[]
  channel?: 'email' | 'sms' | 'push' | 'in-app'
  template?: string
  format?: 'pdf' | 'csv' | 'html' | 'excel'
}

export interface Event {
  uri: string
  name: string
  tags?: string[]
  description: string
  eventType: 'event' | 'delta'
  payload?: SchemaField[]
}

export interface Measure {
  uri: string
  name: string
  tags?: string[]
  description: string
  aggregation?: 'count' | 'sum' | 'average' | 'min' | 'max' | 'rate' | 'ratio' | 'percentile'
  timeWindow?: Duration
  measureType: MeasureStereotype
  unit?: string
  target?: MeasureTarget
}

export interface Function {
  uri: string
  name: string
  tags?: string[]
  description: string
  signature?: FunctionSignature
  body?: FunctionBody
  stereotype?: FunctionStereotype
  purity: FunctionPurity
  cacheable: boolean
  visibility: FunctionVisibility
}

export interface DataSource {
  uri: string
  name: string
  tags?: string[]
  transport?: DataSourceTransport
  endpoint: string
  credentialRef: string
  authType: DataSourceAuthType
  config: Record<string, unknown>
  connectionStatus: DataSourceConnectionStatus
  stereotype?: DataSourceStereotype
  environment: DataSourceEnvironment
  acceptsSimulationTraffic: boolean
}

export interface Pipeline {
  uri: string
  name: string
  tags?: string[]
  mapping?: PipelineMapping
  strategy: PipelineStrategy
  direction: PipelineDirection
  schedule?: PipelineSchedule
  rateLimit?: RateLimitConfig
  stereotype?: PipelineStereotype
  lastRunAt?: string
  lastRunStatus?: PipelineRunStatus
}

export type BmFunction = Function

export interface FacetTypeMap {
  things: Thing
  personas: Persona
  ports: Port
  actions: Action
  workflows: Workflow
  interfaces: Interface
  events: Event
  measures: Measure
  functions: BmFunction
  datasources: DataSource
  pipelines: Pipeline
}

export type FacetArrays = { [K in FacetType]: FacetTypeMap[K][] } & { [key: string]: Facet[] }

export type Facet = Thing | Persona | Port | Action | Workflow | Interface | Event | Measure | Function | DataSource | Pipeline

export interface FacetContainer {
  uri: string
  name: string
  description: string
  facets: FacetArrays
  customFacets?: Record<string, Facet[]>
  symbols: Symbol[]
}

export interface RootContext extends FacetContainer {
  contexts: Record<string, Context>
  links: Link[]
  assertions?: Assertion[]
  customTypes?: UserDefinedEntityType[]
  valueTypes?: ValueTypeDef[]
  meta: { createdAt: string; updatedAt: string }
  tags?: string[]
  aiInstructions?: string
  schemaVersion?: number
}

export interface Context extends FacetContainer {
  parentUri: string
  domainType?: 'core' | 'supporting' | 'generic'
  metadata?: Record<string, unknown>
  tags?: string[]
  aiInstructions?: string
}

/**
 * Inheritance resolution result for Things connected via the `extends` predicate.
 * Use `resolveInheritedAttributes(root, thingId)` from lib/core/inheritance.ts.
 */
export interface InheritedAttributes {
  own: ThingAttribute[]
  inherited: Array<ThingAttribute & { inheritedFrom: string; inheritedFromName: string }>
  all: ThingAttribute[]
  chain: Array<{ uri: string; name: string }>
  circular: boolean
}

export interface CustomFacetInstance {
  uri: string
  name: string
  description?: string
  tags?: string[]
  [field: string]: unknown
}

export interface SubtreeFacet {
  item: Facet
  sourceContextUri: string
  sourceContextName: string
  isOwn: boolean
}

